### ISSUE TITLE
warnet: Local K8s Image Update

### ISSUE THREAD

**Issue by carlaKC** [carlaKC/attackathon#18]
The warnet k8s dev image is out of date per https://github.com/bitcoin-dev-project/warnet/issues/336.

Right now I'm running with [latest switched out](https://github.com/carlaKC/warnet/commit/b69f27b6c1f1cf0ca9c4e1f9de048ae20196a7d9), we either need to: 
* Address issue in warnet
* Run warnet on a branch with the update

**Comment by pinheadmz** [comment]
https://github.com/bitcoin-dev-project/warnet/pull/341
