### ISSUE TITLE
simln: Exclude targeted node from random payment generation

### ISSUE THREAD

**Issue by carlaKC** [carlaKC/attackathon#19]
Ideally the node that we're attacking won't be sending/receiving random sim-ln payments, because we're testing a forwarding node for this run of the attackathon. 

We need to remove our target node from the `warcli network export` (either manually or built in) to exclude it.

**Comment by carlaKC** [comment]
> Would we define a subset of nodes as victims to exclude them from sim.json?

Yeah that would be ideal (probably only one node for this first attempt). I think we'd want this level of control rather than generalist odd/even logic, at least for the attackathon's usecase.

**Comment by pinheadmz** [comment]
https://github.com/bitcoin-dev-project/warnet/pull/340

**Comment by carlaKC** [comment]
Re-opening because we need to set this in our setup for it to take effect!

**Comment by pinheadmz** [comment]
Ah. I blame GitHub
